### ISSUE TITLE
ttrpc-rust needs organization access of containerd for Codecov

### ISSUE THREAD

**Issue by Tim-Zhang** [containerd/ttrpc-rust#148]
![image](https://user-images.githubusercontent.com/1013713/172985279-710d897c-a56d-49a4-a02d-fb72b8b85e7f.png)

We need the permission for generating code coverage report

@mxpv @dmcgowan @fuweid Could you please help us with this?

**Comment by dmcgowan** [comment]
approved

**Comment by Tim-Zhang** [comment]
@dmcgowan Thank you very much

**Comment by Tim-Zhang** [comment]
@dmcgowan Would you please approve the installation of Codecov app. cc @mxpv 
![image](https://user-images.githubusercontent.com/1013713/173016455-d3e8c0f2-ce67-414b-98b8-7d088dacc613.png)
