### ISSUE TITLE
Empty Proto Hangs Server Streaming RPC

### ISSUE THREAD

**Issue by powturns** [containerd/ttrpc-rust#169]
# Description of problem

If a client makes a request to a server streaming RPC (eg: `rpc DivideStream(Sum) returns (stream Part);`) using a default request (eg: `streaming::Sum { ..Default::default() }`), the call hangs indefinitely. This can easily be observed by modifying the [async-stream-client example](https://github.com/containerd/ttrpc-rust/blob/master/example/async-stream-client.rs#L112) to send an empty `Sum`

The root cause is twofold:
1. Empty / Default proto messages serialize to an empty vector
2. The [server implementation](https://github.com/containerd/ttrpc-rust/blob/master/src/asynchronous/server.rs#L605) does not attempt to deliver an empty payload (I think because it assumes it will be receiving DATA messages soon, but the client sends only the request).

# Expected result

The server processes the request and returns the stream to the client.

# Actual result

The server does not execute the corresponding method. The client waits indefinitely for a response.

**Comment by wllenyj** [comment]
Thanks, @powturns.
We can discuss fix proposals in the golang version, and if there is progress we will make a sync fix.
